version: '3.8'
services:
  backend:
    build: ./back
    container_name: camaras-backend
    ports:
      - "3000:3000"
    volumes:
      - ./back/cameras.json:/app/cameras.json
      - ./back/streams:/app/streams
      - ./back/videos:/app/videos
      - ./back/.env:/app/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  frontend:
    build: ./ultimoprompt
    container_name: camaras-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
