version: '3.8'
services:
  backend:
    build: .
    container_name: camaras-backend
    ports:
      - "3000:3000"
    volumes:
      - ./cameras.json:/app/cameras.json
      - ./streams:/app/streams
      - ./videos:/app/videos
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
