version: "3.9"
services:
  frp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frp-server
    ports:
      - "3000:3000"
    volumes:
      - ./cameras.json:/app/cameras.json
      - ./streams:/app/streams
      - ./videos:/app/videos
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
volumes:
  pgdata:
