version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frp-server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: dbbelgranomotos
    restart: always
    environment:
      POSTGRES_DB: belgranomotos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
