## config/frps.toml
```toml
[common]
bind_port = 7000
vhost_http_port = 8080     # opcional para HTTP healthchecks
dashboard_port = 7500      # UI de FRP
dashboard_user = "admin"
dashboard_pwd  = "secret"

# mapeo RTSP
[rtsp]
type = "tcp"
local_ip = "127.0.0.1"
local_port = 8554
remote_port = 18554
```

---